### ISSUE TITLE
Feature request:  Repeating Alarm

### ISSUE THREAD

**Issue by ottobaer** [ncosgray/cuppa_mobile#107]
Hi, 

I  really like the app but the one thing that always bothered me is that the alarm sound just plays once. 

It would be nice if there could be a repeating alarm that needs to be acknowledged or maybe just an option to replay the sound x-times once the timer has finished. 

Thank You,

**Comment by ncosgray** [comment]
Thanks for the suggestion. I like this idea!

While a repeating alarm sound is not possible at all on iOS, we do have some options on Android devices. I have found two options so far. First, I did a quick experiment with an "insistent" notification sound and it is very annoying -- the sound plays in a continuous loop, without pausing, until you dismiss the notification. This is definitely not what I want. So, my idea is to go with the second option I've identified, which is to use a vibration pattern that repeats a couple of times over a few seconds. Do you agree this might be a good compromise?

**Comment by ottobaer** [comment]
I think a vibration pattern is a good idea, it is not as annoying as the alarm sound and still gives a good reminder.

**Comment by ncosgray** [comment]
Sounds good. This will be in the next version of Cuppa (to be released in a couple of weeks), so let me know what you think.

**Comment by ncosgray** [comment]
Cuppa 2.0.0 includes the new vibration pattern, but please note: you will likely need to reinstall the app to get the new notification config. This is because of Google's enforced limits that prevent apps from changing notification settings after the user has already approved them. The only way to "reset" notification settings for an app is to uninstall the app, install it again, and then re-approve it to send notifications. Luckily this to be a painless process as long as you have allowed Google to back up your apps -- you won't lose any of your custom teas.
