### ISSUE TITLE
Feature request: More temperature steps

### ISSUE THREAD

**Issue by felschr** [ncosgray/cuppa_mobile#118]
**The problem:**
Hi, love Cuppa. However, Japanese green teas are commonly brewed with temperatures below 60 ℃ but cuppa doesn't have steps between 20 ℃ & 60 ℃.

**Proposed solution:**
I'd suggest at least adding 50 ℃ & 55 ℃, but perhaps it might be best to just add all 5 ℃ steps in-between.

**Comment by ncosgray** [comment]
Thank you for this excellent suggestion! I will definitely add the 50C and 55C temperature steps (and the rough equivalent temperatures in Fahrenheit). It gets slightly more complicated with temperatures cooler than 50C, due to the over-simplified way that Cuppa infers temperature units based on a 100C cutoff. If there's a need for temperatures between 20-50C I can look at doing some additional refactoring.

**Comment by ncosgray** [comment]
Thanks again! Look for the extra temp settings (50-55C) in the next version of Cuppa. 😄
