### ISSUE TITLE
Feature request: Brewing style and infusions' tracker

### ISSUE THREAD

**Issue by serrq** [ncosgray/cuppa_mobile#133]
Most of us probably use the tea pods, however there is another option: the loose leaves.

So for those that have this style is need for a more accurate brewing control, like:

• grams/100ml

Teas like Bancha (Hojicha) can be infused up to three times before the end of its life.

So an infusion tracker makes sense.

![1000102167](https://github.com/ncosgray/cuppa_mobile/assets/113377431/c6b3705f-eebd-40c7-bbcd-0ddc2ba811a7)

**Comment by ncosgray** [comment]
Thank you for your suggestions! Ideas like these inspire me make this little app better and better.

The new release, version 2.7.0, includes an option to track brewing ratios for each tea you add to the app. I hope you find it useful!

I don't have any plans to add an infusion counter to Cuppa, however. I understand most people achieve this by adding a separate tea button for each infusion: Green Tea Infusion 1, Green Tea Infusion 2, etc. That way you can also customize steep times and temperatures and other options, since each subsequent infusion may need to be done in a different way from the last one.
