### ISSUE TITLE
in_app_review is not-FOSS

### ISSUE THREAD

**Issue by licaon-kter** [ncosgray/cuppa_mobile#149]
ref: https://github.com/ncosgray/cuppa_mobile/pull/147/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25R37

ref: https://github.com/britannio/in_app_review/blob/master/in_app_review/android/build.gradle#L53-L55

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/6cc2fbd24b88c10be090263212cfae311365deb3

**Comment by ncosgray** [comment]
Oh no!

For F-Droid users, the in_app_review code is obviously never called, because that would be meaningless:

https://github.com/ncosgray/cuppa_mobile/blob/5f8dc8be9c602ef59890420bf36319a14e584d19/lib/common/helpers.dart#L168-L172

However, I understand it's a concern to include in_app_review as a dependency nonetheless. I will see if I can create a flavor of the app with this plugin and all related code omitted. It'll probably look similar to the method outlined [here](https://dev.to/deskangel/how-flutter-does-conditional-compilation-5a5m).

This is likely to involve customizing the "flutter build" command F-Droid runs to build the app. @licaon-kter should I coordinate with you if changes are needed on the F-Droid side?

**Comment by licaon-kter** [comment]
Sure, ping when ready to test

**Comment by ncosgray** [comment]
@licaon-kter I created an alternate app entry target, main_fdroid.dart, that disables in_app_review by replacing the function with a no-op.

I believe this should do the trick -- but F-Droid's Flutter build command needs to be tweaked in order to fully remove the non-FOSS library. First remove the in_app_review dependency with a "flutter pub remove" command, and then you can pass the new target to "flutter build" in a parameter. I have added my test script to the repo which demonstrates the sequence of commands: 

https://github.com/ncosgray/cuppa_mobile/blob/90460fdaf6681fd07398c1b2a867b5e8c5e59e3d/build_fdroid.sh#L2-L3

This is still only in a dev branch for now, but could you go ahead and test please? The branch including all changes is [fdroid-flavor](https://github.com/ncosgray/cuppa_mobile/tree/fdroid-flavor). I hope you can temporarily point the F-Droid build process to this branch for a quick test? Let me know, thanks.

**Comment by licaon-kter** [comment]
Trying https://github.com/ncosgray/cuppa_mobile/commit/90460fdaf6681fd07398c1b2a867b5e8c5e59e3d 

The recipe does:
```
flutter config --no-analytics
flutter pub remove --offline in_app_review
flutter build apk --target lib/main_fdroid.dart
```
but that fails:

```
+ /home/vagrant/build/srclib/flutter/bin/flutter pub remove --offline in_app_review
Downloading Material fonts...                                    1,501ms
Downloading Gradle Wrapper...                                       85ms
Downloading package sky_engine...                                  864ms
Downloading flutter_patched_sdk tools...                         1,844ms
Downloading flutter_patched_sdk_product tools...                 1,578ms
Downloading linux-x64 tools...                                     13.3s
Downloading linux-x64/font-subset tools...                         910ms
Resolving dependencies...
Because cuppa_mobile depends on patrol any which doesn't exist (could not find package patrol in cache), version solving failed.

Try again without --offline!
```

**Comment by ncosgray** [comment]
That's unexpected! I use patrol for unit testing, and it is only a dependency for development in [pubspec.yaml](https://github.com/ncosgray/cuppa_mobile/blob/fdroid-flavor/pubspec.yaml).

It should be ok to remove the patrol dependency for building. Try adding another pub remove, e.g.:
`flutter pub remove --offline patrol`

Thanks for your help with this.

**Comment by licaon-kter** [comment]
if I put it before `flutter pub remove --offline in_app_review` it fails like:
```
+ /home/vagrant/build/srclib/flutter/bin/flutter pub remove --offline patrol
Downloading Material fonts...                                      708ms
Downloading Gradle Wrapper...                                       58ms
Downloading package sky_engine...                                  288ms
Downloading flutter_patched_sdk tools...                           655ms
Downloading flutter_patched_sdk_product tools...                   553ms
Downloading linux-x64 tools...                                      5.0s
Downloading linux-x64/font-subset tools...                         547ms
Resolving dependencies...
Because cuppa_mobile depends on flutter_lints any which doesn't exist (could not find package flutter_lints in cache), version solving failed.

Try again without --offline!
```

if I put if after `flutter pub remove --offline in_app_review` it fails as:
```
+ /home/vagrant/build/srclib/flutter/bin/flutter pub remove --offline in_app_review
Downloading Material fonts...                                      583ms
Downloading Gradle Wrapper...                                       54ms
Downloading package sky_engine...                                  238ms
Downloading flutter_patched_sdk tools...                           526ms
Downloading flutter_patched_sdk_product tools...                   452ms
Downloading linux-x64 tools...                                      4.3s
Downloading linux-x64/font-subset tools...                         300ms
Resolving dependencies...
Because cuppa_mobile depends on patrol any which doesn't exist (could not find package patrol in cache), version solving failed.

Try again without --offline!
```

**Comment by ncosgray** [comment]
I’m learning more about Flutter dependency management from this conversation. :) I’m still a bit confused about why it is even trying to fetch the dev_dependencies.

Anyway. It seems using the “offline” parameter didn’t let your build process download all the new dependencies other than in_app_review. We need to get those dependencies somehow.

A couple of ideas:
1. Try taking out the “offline” parameter
2. If that doesn’t work, add this command before the “remove” command: `flutter pub cache repair`

**Comment by ncosgray** [comment]
Wonderful! Thank you for working this out. I'll merge the changes into the main branch in a moment.
