### ISSUE TITLE
Specify number of infusion

### ISSUE THREAD

**Issue by Ryuno-Ki** [ncosgray/cuppa_mobile#27]
First of all: thanks for this app!

I was amazed to discover it in the F-Droid app store 😻

One thing I'm missing right now is the ability to tweak the timer depending on the number of infusion I'm making right now.

Is it possible to add this without having to reconfigure the tea timer every time?

**Comment by ncosgray** [comment]
Thank you for the suggestion, and I'm so glad you like my little app!

Although the total of only three tea settings in the app is a limiting factor, you could certainly do this right now by editing the teas. For example, I could set up a tea with the name "Oolong - 1st" and another named "Oolong - 2nd", with the steep times you prefer for the first and second infusion, respectively.

I think this will largely be resolved by issue https://github.com/ncosgray/cuppa_mobile/issues/20 when I add more teas to Cuppa, because then it won't be so limiting to set up different infusions separately. What do you think?

**Comment by Ryuno-Ki** [comment]
From what I've read, it would rather be a reopen of #5.

I drink different kinds of tea (green, black, herbal infusion).
I'm fine with folding this issue into #5.
Shall I close it?

**Comment by ncosgray** [comment]
My plan to address #20 is to keep a minimum of 3 teas, but also allow users to add additional custom teas, remove unneeded teas (as long as at least 3 remain), and reorder all the teas that they have set up in preferences. This should cover #5 as well as this issue too, I hope.

I'm closing this to consolidate the "more teas" work into a single issue, #20.
