### ISSUE TITLE
Feature request: Custom tea colors

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#48]
Currently the teas have some preset colors.

(Maybe) it would also be nice if below the presets there would be a color picker, that would enable you to select from a more colorful color palette.

**Comment by ncosgray** [comment]
I'm adding a few more tea colors for the next version, but will eventually implement a full color picker as well. It's a bit complicated because the color must be legible against either a dark or light background. I hope to be able to address that by providing a sample swatch showing what the chosen color would look like on both background colors, as part of the color picker UI.
