### ISSUE TITLE
Feature request: Custom (hours longer) timers for Cold Brewing tea

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#57]
Current issue:
- Teas can also be cold brewed and it's very good if done so. "You can cold steep your teas for as little as 2 hours or even as long as 12 hours and more."
- Cuppa currently supports max 19 minutes and 45 seconds

Suggested feature:
- Please add an option to set custom timers, so you can brew 6, 12, 24 hours (or any preffered amount) etc...
- At the end of the minutes or seconds, there  could be a "Set custom time" option, where you can then enter it manually, including hours.
- Add a toggle "include cold brewing", which would enable setting hours and custom cold temperatures.

![image](https://user-images.githubusercontent.com/50620416/141682994-d8392868-1e74-4e13-a028-7da9aa9a4b02.png)
Source: [Theteacupoflife](https://theteacupoflife.com/2017/06/how-to-cold-steep-tea-and-why.html)

**Comment by ncosgray** [comment]
I have some concerns about this:
1. Reliability of Android notifications is already somewhat hit-and-miss, especially with certain phone makers that aggressively limit background tasks. I think long-running tasks would be less reliable.
2. The ability of a Cuppa timer to survive a device reboot is a question mark.
3. If there is already a cold steep timer running, when users would not be able to time their afternoon cup of hot tea.

1 and 2 could be tested and perhaps wouldn't end up being problems. The third concern is a bigger problem, in my view. I will revisit this feature request in the future after enabling multiple simultaneous tea timers in the app.

**Comment by aha999** [comment]
Maybe a button that would redirect to the system timer would be useful so it can be used instead, since it's probably more reliable. Also, maybe Cuppa can have an optional permission, so it can run in the background, regardless of being opened or not.

**Comment by with0utt** [comment]
i would really like to see this addition as i exclusively cold brew my tea. as long as i can still use another timer simultaneously to cold brew multiple teas at once, it would be really useful

**Comment by ncosgray** [comment]
Thanks for the bump, @with0utt. Now that the app supports multiple timers I'm taking another look at this request.

**Comment by ncosgray** [comment]
There's a lot of work still to be done in the UI, but [Cuppa 1.9.0](https://github.com/ncosgray/cuppa_mobile/releases/tag/1.9.0) includes provisional support for tea times suitable for cold brewing. In 1.9.0 you are able to select brew times up to 999 minutes -- or over 16 hours.

I have found the notifications for long-brewing teas to be reliable on my Pixel phone. But unfortunately, I do not have the ability to test on devices from other manufacturers like Huawei or Xiaomi or even Samsung, so I cannot say with certainty if this will work well for everyone. Please give it a try and let me know!

At the moment I consider this to be something of an "experimental" feature. Those who look for it will figure out how to do it, but support for cold-brew time periods isn't fully tested yet, so it's somewhat hidden. You'll actually have to keep scrolling the minutes selector wheel until you reach the hundreds. Not exactly convenient or intuitive...

Assuming we find that the notifications are still reliable for hours-long timers, I plan to greatly improve the user experience for cold brewing in the next version of Cuppa:
* I'll add a cold brew tea preset to the Add Tea dialog with a default steep time of 12 hours. Let me know if there is a better default time.
* Instead of selecting minutes (e.g. 720 minutes for a 12-hour cold brew) you'll be able to select hours and minutes when you edit a tea's steep time. Most likely that'll take the form of a toggle to switch between an hh:mm selector and a mm:ss selector.
* Brew timers will show hours-long timers with an "hours" indicator rather than the typical hh:mm format. The indicator will be a localized abbreviation. For example, I believe "12h00m" makes sense in many languages, but perhaps for Chinese speakers something like "12时00分" is better. I'm hoping Weblate translators will be able to help with the abbreviations.

**Comment by ncosgray** [comment]
Cuppa 2.0 will be released soon with full support for cold brew tea timers!

**Comment by aha999** [comment]
This is awesome!!
