### ISSUE TITLE
Feature request: remove notification upon entering the app

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#66]
**The problem:** Currently, when the app is minimized and the timer finishes, the notification shows up, but when you open the app, the notification doesn't disappear.

**Proposed solution:** If possible, remove the notification, after you enter the app.

**Comment by ncosgray** [comment]
This was an intentional design choice. Here is my reasoning. Keeping the notification until it is intentionally dismissed allows the user to keep track of which tea finished brewing and when it finished, since that info isn't displayed in the app after the timer ends. Those pieces of info are present only in the notification. I expect notification details will become more useful when I add the ability to set 2 timers at once (see #63).

Although unfortunately, I just noticed the second piece of info -- when the timer finished -- isn't actually being included in the notification on Android (it is on iOS). I opened bug report #67 which will be fixed in the next version.

**Comment by ncosgray** [comment]
Unfortunately, it isn't trivial to implement an automatic notification clear on opening the app, especially with a Flutter app. In addition, this functionality isn't supported on iOS. For these reasons I am closing this issue.

The best way to dismiss the timer notification with the fewest clicks is to tap the notification itself instead of opening the app from your launcher.
