### ISSUE TITLE
Bug report: Two timers in row - second timer no notification

### ISSUE THREAD

**Issue by sandoxy** [ncosgray/cuppa_mobile#71]
I have 3 custom timers. Sometimes I start one timer and get a notification after time is up. I instently start another timer, but then I never get a notification after time is up. The notification starts whenever I open the app next time.

**Comment by ncosgray** [comment]
Hello and thanks for your feedback about Cuppa!

I don't see this behavior on my Android or iOS devices, or in any of the emulators, so I will need more information...
1. What is your device operating system and version?
2. Which version of Cuppa are you using?
3. Are you starting the tea timers from the buttons on the app's main screen, or are you starting timers using shortcuts from your launcher?
4. Do you dismiss the previous timer notification before starting a new timer?
5. Have you checked your notification settings in the operating system? The settings location varies by device, but for example: Settings > Notifications > App Settings > Cuppa > Timer Notifications.

I also want to share that the latest 1.5.5 release includes some Android SDK and permissions changes affecting notifications. Version 1.5.5 is live in the Apple and Google app stores but F-Droid doesn't appear to have published it as of right now. If you're using F-Droid to install Cuppa, I'd recommend upgrading to Cuppa 1.5.5 whenever it's available, because that may fix the problem you're having.

**Comment by ncosgray** [comment]
Awesome. I'm so glad to hear that!
