### ISSUE TITLE
Feature request: Shortcut to system sound notifications for Cuppa

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#90]
**The problem:** Currently, users have to navigate to system settings to change the notification sound for Cuppa, which only tech-savvy people can do.

**Proposed solution:** Include a shortcut button in the Cuppa app, that leads to the system sound notification setting for Cuppa app.

**Comment by ncosgray** [comment]
I've looked into this, and I think the best I'm able to do is what is already in the app: a link to the Cuppa notification settings (the "Open your device's system settings..." link). There doesn't seem to be a way to deep-link any further into the settings than that -- which is a bit unfortunate since most settings are an additional tap away. Still, I think it is an acceptable entry point.
