### ISSUE TITLE
Feature request: AMOLED Black theme

### ISSUE THREAD

**Issue by Z1xus** [ncosgray/cuppa_mobile#91]
**The problem:** The app has dark and light themes, but no pure black theme. Pure back theme would have more contrast and would consume less battery on AMOLED screens 

**Proposed solution:** Add theme with the pure black background, maybe adjust colors of buttons and frames to correspond the theme.
I made a quick example of how it could look like:<details>
  <summary>Screenshot</summary>

![Screenshot_20221112-141138](https://user-images.githubusercontent.com/40185941/201476709-67a2540c-f471-4f62-8ae6-9d69c5fa1deb.png)
</details>

**Comment by ncosgray** [comment]
Hello, and thanks for the suggestion!

Cuppa doesn't pick its own colors aside from the highlight color (blue). Instead, I simply let the Flutter framework use the per-OS/per-mode defaults. On Android, that means following the standard [Material Design](https://m2.material.io/design/color/dark-theme.html) which for dark mode defaults to gray rather than black. The Material guidelines only recommend using pure black for apps that "require efficient battery usage". I'm not sure Cuppa falls into that category since it is typically the foreground app for only a short time (to set a timer).

Regardless, I do like this idea and will look into what it would take to implement a pure black theme. I plan to experiment with color palettes that work on top of a pure black background, and I will look at recreating the Cuppa graphics in such a way that there is still contrast with the cup's dark border even when the background is black.
