### ISSUE TITLE
Feature request: dark mode (gray) to be separate from black mode

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#93]
**The problem:** in a new update, gray background was replaced by a completely black background, which looks weird.

**Proposed solution:** Make black theme an optional setting and make dark theme default

**Comment by ncosgray** [comment]
Related: issue #91.

I'm so sorry you don't like the new pure black theme! I spent quite a lot of time honing it until I liked it -- I was pretty skeptical at first, myself. I actually prefer the pure black theme now, though, because it's easier on my eyes first thing on a winter's morning before the sun rises. :)

I'd prefer not to have two different dark themes in the app. It would be better if a single dark theme could work well for everyone. Can you think of any adjustments to the pure black theme that would make it less "weird" in your view?

**Comment by aha999** [comment]
I agree of your use case scenario and it's superb if it's intended like that. 
On the other hand, many apps have more options in the themes section. It would be nice to have the Dark (grey) option back. Options are usually:
- Follow system settings
- Light theme
- Dark theme (dark grey)
- Amoled (pure black)
