### ISSUE TITLE
Feature request: Open directly from lockscreen

### ISSUE THREAD

**Issue by kennioje** [ncosgray/cuppa_mobile#94]
I have Cuppa as a shortcut on my android lockscreen.
Currently you have to unlock the device when the shortcut is pressed. It would be great to not have to do so, making it much easier to start the timer.
This appears to be a flag set on the activity. (FLAG_SHOW_WHEN_LOCKED)

**Comment by ncosgray** [comment]
Hello, and thanks for your suggestion!

If understand correctly, you've been able to add a shortcut to Cuppa on your lock screen? I'm not familiar with this functionality -- and my Pixel phone can't do this -- but it sounds super useful, and I'd like to try to make Cuppa work better in that context. I did a little research and it seems some phone manufacturers have added similar functionality to their custom flavors of Android. For example, Samsung lets Galaxy users add custom lock screen shortcuts, per [this article](https://www.samsung.com/au/support/mobile-devices/customise-lock-screen-shortcuts/).

Since lock screen app shortcuts are not supported in stock Android, could you tell me what device you are using and what version of Android? That will help me investigate if there are any options.

Also, where did you find info about the FLAG_SHOW_WHEN_LOCKED flag on the app activity? This flag was deprecated with Android 8.1 ([reference](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SHOW_WHEN_LOCKED)) and I am unsure if the new method will have the same effect.

**Comment by ncosgray** [comment]
There have been some rumors that Google may add custom lock screen shortcut functionality to Android 14, so I'm going to wait and see what happens there.

In the meantime, @kennioje, can you confirm what device and Android version you're using?

**Comment by ncosgray** [comment]
Today, I was able to experiment with adding FLAG_SHOW_WHEN_LOCKED to Cuppa, along with the FLAG_DISMISS_KEYGUARD which I found in some discussions of lock screen functionality. I tested Cuppa on a Galaxy S23 emulator's lock screen, with each flag individually and also with the combination of both flags. Adding these flags does not allow Cuppa to be opened from the lock screen without unlocking the device. Cuppa can be added as a shortcut but it is always in the "requires unlock" category. I scoured the internet but I cannot find any documentation from Samsung about giving developers the ability to override this setting. I believe it is not possible (probably for security reasons, to prevent users from bypassing device locks).

I've also done some more research on the lock screen functionality that will be added with Android 14, and it turns out that users will not be able to add any app as a shortcut -- Android 14 will limit it to certain system apps/functions. We won't have the ability to add a lock screen shortcut for Cuppa.

I am closing this issue because I think it is impossible to achieve the requested behavior.
